# Page tree
pages:
- index.md
- Extensions.md

# Project information
site_name: Markdown Rundown
site_description: Markdown Rundown
site_author: Adam Twardoch
site_url: https://twardoch.github.io/markdown-rundown/

# Repository
repo_name: markdown-rundown
repo_url: https://github.com/twardoch/markdown-rundown

# Copyright
copyright: Copyright © 2017 by Adam Twardoch

# Documentation and theme
theme: material
#theme_dir: mkthemes/material-extra/
extra_css: []
extra_templates: []

# Options
extra:
  version: 2017.01.12
  palette:
    primary: grey
    accent: indigo
  font:
    text: PT Sans Caption
    mono: Roboto Mono
  social:
    - type: github-alt
      link: http://twardoch.github.io/markdown-rundown/
    - type: adamtwar
      link: https://twitter.com/adamtwar

docs_dir: 'wiki/'
site_dir: 'docs/'
use_directory_urls: true

site_favicon: null
edit_uri: null

# Extensions
markdown_extensions:
- tables
- abbr
- attr_list
- admonition
- codehilite:
    css_class      : 'code'
    linenums       : null
    guess_lang     : true
    use_pygments   : true
    pygments_style : 'default'  
- def_list
- footnotes:
    PLACE_MARKER   : '///Footnotes Go Here///' 
    # if the place marker text is not found in the document, 
    # the footnote definitions are placed at the end of the resulting HTML document
    UNIQUE_IDS     : false
    BACKLINK_TEXT  : '&#8617;'  
- meta
- nl2br
- smarty:
    smart_dashes           : true  # convert dashes
    smart_quotes           : true  # convert straight quotes
    smart_angled_quotes    : false # whether to convert angled quotes
    smart_ellipses         : true  # whether to convert ellipses
    substitutions:                 # overwrite default substitutions
        left-single-quote  : '‘'   # '
        right-single-quote : '’'   # '
        left-double-quote  : '“'   # "
        right-double-quote : '”'   # "
        left-angle-quote   : '«'   # <<
        right-angle-quote  : '»'   # >>
        ellipsis           : '…'   # ...
        ndash              : '–'   # --
        mdash              : '—'   # ---
- toc:
    permalink      : '»'
    marker         : '[TOC]'
    title          : 'Table of Contents'
    anchorlink     : false
    baselevel      : 1
    separator      : '-'
- pymdownx.betterem:
    smart_enable   : 'all'                # 'all' | 'asterisk' | 'underscore' | 'none'
- pymdownx.magiclink:
    hide_protocol  : true
- pymdownx.mark:
    smart_mark     : true                 # Allows for ==mark==me== 
- pymdownx.superfences:
    disable_indented_code_blocks : false
    nested         : true
    uml_flow       : false
    uml_sequence   : false
- pyembed.markdown
- markdown_include.include:
    base_path      : 'wiki/'
    encoding       : 'utf-8'
- sections
- outline
- cite
- steroids.wikilink
- steroids.kbd:
    repl_mac       : true                # Replace macOS symbols
    html_class     : 'kbd'                # CSS hook. Leave blank for none
- steroids.replimgsrc: 
    find           : 'https://github.com/Fontlab/FontLabVI-help/blob/master/images/'
    replace        : '../img/'  
- custom_span_class
- figcap
- fontawesome_markdown
#- collapse # BUGGY
